FROM oraclelinux:9
###
# rpmbuild/Dockerfile_EL9
# https://github.com/furplag/archive/docker
#
# Licensed under CC-BY-NC-SA 4.0 ( https://creativecommons.org/licenses/by-nc-sa/4.0/ )
#
# a disposable workbench to build RPM package .
#

###
# ENV / variable
###

ARG LC_ALL
ARG TZ=Etc/UTC
ARG RPMBUILD_GROUP=rpmbuild
ARG RPMBUILD_USER=rpmbuild

ARG RPMBUILD_GROUP_ID
ARG RPMBUILD_USER_ID

ARG REPO_URL
ARG REPO_NAME

ARG GPG_KEY
ARG GPG_PRIVATEKEY
ARG GPG_PRIVATEKEY_PASSPHRASE

###
# process
###

# packages
RUN dnf config-manager --enable ol9_{codeready,distro}_builder && \
  if [ -n "${REPO_URL:-}" ] && [ -n "${REPO_NAME:-}" ]; then dnf config-manager --add-repo ${REPO_URL} && dnf config-manager --enable ${REPO_NAME}; fi && \
  dnf clean all && dnf upgrade -y && \
  dnf install -y oracle-epel-release-el9 && dnf clean all && dnf upgrade -y && \
  dnf group install -y 'Development Tools' 'RPM Development Tools' && \
  dnf install -y createrepo pinentry rpmdevtools sudo && \
  dnf clean all;

# user / group
RUN groupadd -g ${RPMBUILD_GROUP_ID} ${RPMBUILD_GROUP} && \
  useradd -m -r -u ${RPMBUILD_USER_ID} -g ${RPMBUILD_GROUP_ID} -d /home/${RPMBUILD_USER} -s /sbin/nologin ${RPMBUILD_USER} && \
  usermod -aG wheel ${RPMBUILD_USER} && echo '%wheel ALL=NOPASSWD:ALL' >/etc/sudoers.d/999_rpmbuild;

WORKDIR /home/${RPMBUILD_USER}
USER ${RPMBUILD_USER}

# signing key
COPY ${GPG_KEY} /home/${RPMBUILD_USER}/
COPY ${GPG_PRIVATEKEY} /home/${RPMBUILD_USER}/

RUN gpg --import ~/${GPG_KEY}
RUN gpg --import --allow-secret-key-import --batch --passphrase=${GPG_PRIVATEKEY_PASSPHRASE} /home/${RPMBUILD_USER}/${GPG_PRIVATEKEY}
RUN sudo rpm --import /home/${RPMBUILD_USER}/${GPG_KEY}
RUN rpmdev-setuptree;

RUN echo -e "\n\
%_signature gpg\n\
%_gpg_name @_@GPG_KEY_ID@_@\n" >>~/.rpmmacros && \
  __gpg_name="$(gpg -k | grep -E '^\s' | sed -e 's/^\s\+//g' -e 's/^.*\///g' -e 's/\s.*$//g')" && \
  sed -i -e "s/@_@GPG_KEY_ID@_@/${__gpg_name}/" ~/.rpmmacros;

# cleanup
WORKDIR /
USER root
RUN dnf clean all && rm -rf /tmp/*;

VOLUME [ "/home/${RPMBUILD_USER}" ]

WORKDIR /home/${RPMBUILD_USER}
USER ${RPMBUILD_USER}

ENTRYPOINT [ "/bin/bash" ]
