# rpmbuild/el9/docker-compose.yml
services:
  el9:
    build:
      context: .
      args:
        RPMBUILD_GROUP: ${RPMBUILD_GROUP}
        RPMBUILD_GROUP_ID: ${RPMBUILD_GROUP_ID}
        RPMBUILD_USER: ${RPMBUILD_USER}
        RPMBUILD_USER_ID: ${RPMBUILD_USER_ID}
        GPG_KEY: ${GPG_KEY}
        GPG_PRIVATEKEY: ${GPG_PRIVATEKEY}
        GPG_PRIVATEKEY_PASSPHRASE: ${GPG_PRIVATEKEY_PASSPHRASE}
        GPG_KEY_ID: ${GPG_KEY_ID}
    env_file: .env
    container_name: rpmbuild-el9
    volumes:
      - type: volume
        source: rpmbuild_el9_data
        target: /home/rpmbuild
    stdin_open: true
    tty: true

# must be add permissions to RPMBUILD_USER to handles data .
volumes:
  rpmbuild_el9_data:
    name: rpmbuild_el9_data
    external: true
