# valheim-aarch64.oci.ampere/docker-compose.yml
services:
  server:
    build: .
    env_file: ./.env
    container_name: ${VALHEIM_NAME}
    ports:
      - "0.0.0.0:${VALHEIM_PORT}-${VALHEIM_PORT_ASIDE}:${VALHEIM_PORT}-${VALHEIM_PORT_ASIDE}/udp"
    volumes:
      - type: volume
        source: steamapp_data
        target: /opt/steam
    stdin_open: true
    tty: true

# must be add permissions to STEAM_USER to handles data .
volumes:
  steamapp_data:
    name: valheim_server_data
    external: true
